version: '3'

services:
  netobject-status-sync:
    env_file:
      - .env
    build:
      context: .
      dockerfile: deployment/Dockerfile.prod
    network_mode: "host"
    restart: "always"
    volumes:
      - ./configs:/configs
